name: CI - Integración Continua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Stage 1: Checkout del código
      - name: Checkout del código
        uses: actions/checkout@v4

      # Stage 2: Configurar Python 3.13
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Stage 3: Crear virtualenv e instalar dependencias
      - name: Crear virtualenv e instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Stage 4: Instalar Snyk CLI
      - name: Instalar Snyk CLI
        run: npm install -g snyk

      # Stage 5: Escaneo de vulnerabilidades con Snyk
      - name: Escaneo de vulnerabilidades con Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          run: snyk orgs
        run: |
          source venv/bin/activate
          snyk test --file=requirements.txt --org=ing.luisgonzalez1994 --severity-threshold=high

      # Stage 6: Ejecutar pruebas unitarias
      - name: Ejecutar pruebas
        run: |
          source venv/bin/activate
          pytest tests/ -v

      # Stage 7: Construir imagen Docker
      - name: Build imagen Docker
        run: docker build -t devops-app .
